### ISSUE TITLE
Интересный проект

### ISSUE THREAD

**Issue by honix** [borodust/cludge#1]
Во-первых, хочу сказать - как классно, что лисп комьюнити постоянно растет и пополняется новыми проектами! 

Мне стала интересна идея этого проекта. Каким вы видите "visual editor for cl-bodge"? Я полагаю, вы хотите сделать что-то типа игрового движка, аля Unity, UE4, Godot. С динамической природой лиспа можно сделать что-то действительно интересное.

**Comment by borodust** [comment]
Упс! Вот это я мощно пропустил issue :D Только сейчас заметил. Мои извинения. Сам движок называется `cl-bodge`, а этот проект предназначен для выполнения каких-то визуальных задач для него  К примеру, мне это нужно, чтобы в WYSIWYG-стиле привязывать rigid bodies физического движка к скелету и т.п. по мелочи.

В связи с определенными обстоятельствами пришлось приостановить этот проект (основной движок требует определенного тюнинга для интеграции с подобной тулзой). Через месяц или два планирую вернуться к нему.
